### ISSUE TITLE
Assistant Developer

### ISSUE THREAD

**Issue by Scuph** [Scuph/ScuphsUtilities#1]
As Above

@LegendIsAwesomes? @tylerhyperhd? @VJGamingUK?

Interested?

**Comment by LegendIsAwesomes** [comment]
Im interested. What is being made?

**Comment by Scuph** [comment]
@LegendIsAwesomes Asyou can see, I rewrote this plugin to be server configurable and just overall better.

**Comment by LegendIsAwesomes** [comment]
Okay. Why not create a entirely new plugin maybe? If you would like to discuss PM me on skype.

**Comment by Scuph** [comment]
Closed.

@JeromSar took that position @LegendIsAwesomes.

**Comment by LegendIsAwesomes** [comment]
@Scuph doesn't he expect pay?

**Comment by Scuph** [comment]
@LegendIsAwesomes Exactly.

**Comment by LegendIsAwesomes** [comment]
@Scuph, your paying him?

**Comment by Scuph** [comment]
@LegendIsAwesomes I think thats none of your business to know, but yes ;)

**Comment by LegendIsAwesomes** [comment]
OK.
